### Original notebook form the video : https://github.com/KeithGalli/NumPy

In [2]:
import numpy as np

##### Basic

In [19]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]],dtype = 'int32')
print(a,'\n',b)

[1 2 3 4] 
 [[1 2 3 4]
 [5 6 7 8]]


In [24]:
# Get Shape
b.shape

(2, 4)

In [25]:
#Get dimensions
b.ndim

2

In [26]:
#Get Data type
b.dtype

dtype('int32')

In [28]:
#Get Size
b.itemsize

4

In [20]:
b.size

8

In [23]:
b.nbytes

32

##### Accessing changing specific elements, rows, columns, etc..

In [30]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [32]:
arr[1][5] 
arr[1,5]

13

In [34]:
# Get specific row
arr[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [35]:
# Get specific column
arr[:,2]

array([ 3, 10])

In [40]:
# Getting little of fancey
arr[1,0:4:2]

array([ 8, 10])

#### 3D

In [43]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
arr3d[:,:,1]

array([[2, 4],
       [6, 8]])

In [50]:
# Matrix of all zeroes
np.zeros((2,3,1))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [52]:
# Matrix of all ones
np.ones((1,2,3))
np.ones((1,2,3),dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1]]])

In [54]:
# Custome number array
np.full((2,2),99)
np.full((2,2),99,dtype= 'int32')

array([[99, 99],
       [99, 99]])

In [57]:
# More like this...0
#np.full_like
np.full_like(a,5)

array([5, 5, 5, 5])

In [59]:
# Random decimal numbers between 0-1
np.random.rand(4,2)

array([[0.10332611, 0.58689052],
       [0.56083302, 0.72103396],
       [0.89277908, 0.99865558],
       [0.97365773, 0.57236944]])

In [62]:
# Make a random array with the dimensions of a 
np.random.random_sample(a.shape)

array([0.51201759, 0.61335508, 0.60648733, 0.28233056])

In [74]:
# Random sample of integers.
np.random.randint(-3,3,size=(3,3))

array([[ 2,  0, -2],
       [ 2, -2,  2],
       [ 2, -3,  1]])

In [77]:
# Create a identity matrix
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [83]:
arr_r = np.array([[1,2,3]])
np.repeat(arr_r,3,axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [90]:
#practice Problem

p1 = np.ones((5,5),dtype= 'int64')
p1[1:4,1:4] = np.zeros((3,3))
p1[2,2] = 9
p1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

#### Be carefull while trying to copy array!!

In [97]:
# Problem
a = np.array([1,2,3])
b = a
b[1] = 100
# If we change b , a changes with it
a , b

(array([  1, 100,   3]), array([  1, 100,   3]))

In [96]:
# Solution
a = np.array([1,2,3])
b = a.copy()
b[1] = 100
a , b

(array([1, 2, 3]), array([  1, 100,   3]))

#### Math


In [102]:
 a = np.array([1,2,3,4,5,6,7])

In [103]:
a -1

array([0, 1, 2, 3, 4, 5, 6])

In [104]:
a + 1

array([2, 3, 4, 5, 6, 7, 8])

In [105]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [108]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [109]:
a ** 2

array([ 1,  4,  9, 16, 25, 36, 49])

In [111]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

#### Linear Algebra

In [124]:
# Matrix multiplication
a = np.ones((2,3),dtype='int32')
b = np.full((3,2),3,dtype='int32')
a ,b , np.matmul(a,b)

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[3, 3],
        [3, 3],
        [3, 3]]),
 array([[9, 9],
        [9, 9]]))

In [123]:
# Determinent

c = np.identity(3)
np.linalg.det(c)

1.0

### For routine and exploration for linear algebra in numpy: https://numpy.org/doc/stable/reference/routines.linalg.html

#### Statistics with numpy

In [126]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
np.min(stats,axis=1)


array([1, 4])

In [130]:
np.max(stats,axis= 1)

array([3, 6])

In [131]:
np.sum(stats,axis =1)

array([ 6, 15])

#### reorganize the arrays

In [149]:
before = np.array([[1,2,3,4,5,1],[4,5,6,7,8,9]])
after = before.reshape((2,2,3))
after

array([[[1, 2, 3],
        [4, 5, 1]],

       [[4, 5, 6],
        [7, 8, 9]]])

#### Vertically static vertices

In [152]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

#### Horizontal stacking 

In [155]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack([h1,h2,h1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

#### Miscellaneous 

##### Load Data from the file

In [161]:
file_data = np.genfromtxt('npFileTempData.txt',delimiter=',',dtype='int16')

#### Boolean masking and advance indexing 

In [162]:
file_data > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
        False],
       [False,  True,  True,  True,  True,  True, False, False, False,
        False]])

In [163]:
file_data[file_data>50]

array([55, 66, 77, 88, 99, 99, 88, 77, 66, 55], dtype=int16)

#### we can index with the list in numpy . Cool!!!

In [164]:
temp_arr = np.array([1,2,3,4,5])
temp_arr[[1,2]]

array([2, 3])

In [169]:
# Which columns has value greater then 50
np.any(file_data > 50,axis = 0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [170]:
#Which rows has values greater the 50 
np.any(file_data > 50, axis = 1)

array([False, False,  True,  True])

In [193]:
# Which rows has all data greater then 3
np.all(file_data > 3 , axis = 1)

array([False, False, False, False])

In [192]:
# Which calumns has all data greater then 3
np.all(file_data > 3 , axis = 0)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [197]:
#Values greater then 10 and less then 50
((file_data > 10) & (file_data < 50))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True]])

In [198]:
#Values not greater then 10 and not less then 50
(~(file_data > 10) & (file_data < 50))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False]])

Questions  1 Blue , 2 Green , 3 Red

![alt text](NumpyQuestions.png "Title")

In [211]:
arr = np.array([np.array(range(1,6)),np.array(range(6,11)),np.array(range(11,16)),np.array(range(16,21)),np.array(range(21,26)),np.array(range(26,31))])

In [210]:
# 1
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [213]:
# 2
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [220]:
arr[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])