### Why numpy?

we can have all types of data in list and it will slow the process down, 
where as numpy don't and it increase the efficiency

In [4]:
import numpy as np

#creating numpy array.
np_arr = np.array([1,2,3,4])
np_arr

array([1, 2, 3, 4])

#### Get the shape(Dimension) of array  

In [26]:
np_arr.ndim # this is 1 dimension array

1

In [27]:
np_arr.shape # this 1 dimension array has 4 elements in it

(4,)

In [30]:
np.array([[1,2,3],[4,5,6]]).shape # this is 2 dimension array which is 3 element in each dimension!! 

(2, 3)

In [31]:
# have numpy range
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#step
# [start,stop,step]
arr2 = np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [12]:
# array of zeros (Can do multi dimensions)
arr3 = np.zeros(3)
arr3

array([0., 0., 0.])

In [16]:
# array of zeros (Can do multi dimensions)
arr4 = np.zeros((3,3))
arr5 = np.zeros((3,3,3))
arr4,arr5

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]))

In [22]:
#array of number you want
# ((shape),number)
arr6 = np.full((3),6)
arr7 = np.full((3,10),6)
arr6 , arr7

(array([6, 6, 6]),
 array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]]))

In [23]:
# from the list to np array
my_list = [1,3,4,5,6,7,8,0]
arr8 = np.array(my_list)
arr8

array([1, 3, 4, 5, 6, 7, 8, 0])

In [ ]:
#