#### Copy vs view

In [25]:
import numpy as np

In [26]:
arr1 = np.arange(10)

In [13]:
arr_view = arr1.view()
    #  or 
arr_view = arr1

In [19]:
print(arr1 , "Original")
print(arr_view , "view")

[88  1  2  3  4  5  6  7  8  9] Original
[88  1  2  3  4  5  6  7  8  9] view


In [15]:
arr_view[0] = 88 

In [34]:
print(arr1 , "Original") # Original changes when we change the view.
print(arr_view , "view")
# as viewing only sort the reference or the pointer of the data from arr1. if we change the data from any of the arr1 or arr_view both will change, as they share the same data.

[0 1 2 3 4 5 6 7 8 9] Original
[88  1  2  3  4  5  6  7  8  9] view


In [27]:
arr1 = np.arange(10)

In [28]:
arr_copy = arr1.copy()

In [29]:
print(arr1 , "Original")
print(arr_copy , "view")

[0 1 2 3 4 5 6 7 8 9] Original
[0 1 2 3 4 5 6 7 8 9] view


In [32]:
arr_copy[0] = 88 

In [33]:
print(arr1 , "Original")
print(arr_copy, "view")

[0 1 2 3 4 5 6 7 8 9] Original
[88  1  2  3  4  5  6  7  8  9] view
