In [4]:
import numpy as np

In [5]:
arr1 = np.arange(10)

In [6]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# square root of each element
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
# Finding absolute value basically remove '-'.
arr2 = np.arange(-5,5)
arr2 , np.absolute(arr2) # see

(array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]),
 array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4]))

In [15]:
#Exponentials..
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
#Finding maximum and minimum
arr2.max() , arr2.min()

(4, -5)

In [20]:
#find the sign(negitive or positive or 0) it returns 0 -> 0 , negitive -> -1  and positive -> 1
np.sign(arr2)

array([-1, -1, -1, -1, -1,  0,  1,  1,  1,  1])

In [23]:
# Sin , cos or log of elements
np.cos(arr2) , np.sin(arr2) , np.log(arr2) # 0 or negitives will not work for log... and 0 will not work for cos and sin

C:\Users\devampathak\AppData\Local\Temp\ipykernel_7324\527691583.py:2: RuntimeWarning: divide by zero encountered in log
  np.cos(arr2) , np.sin(arr2) , np.log(arr2) # 0 or negitives will not work for log... and 0 will not work for cos and sin
C:\Users\devampathak\AppData\Local\Temp\ipykernel_7324\527691583.py:2: RuntimeWarning: invalid value encountered in log
  np.cos(arr2) , np.sin(arr2) , np.log(arr2) # 0 or negitives will not work for log... and 0 will not work for cos and sin


(array([ 0.28366219, -0.65364362, -0.9899925 , -0.41614684,  0.54030231,
         1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362]),
 array([ 0.95892427,  0.7568025 , -0.14112001, -0.90929743, -0.84147098,
         0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([       nan,        nan,        nan,        nan,        nan,
              -inf, 0.        , 0.69314718, 1.09861229, 1.38629436]))

### https://numpy.org/doc/stable/reference/ufuncs.html  
#### explore more univeral functions for numpy here