In [1]:
import numpy as np

In [6]:
#Slicing the array. It's same is we slice string!!
arr1 = np.arange(0,13)
arr1[0:5] # this returns the first 4 items. 

array([0, 1, 2, 3, 4])

In [8]:
# this return from index 4 (5th item ) to the end. 
arr1[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# Negative slices
arr1[-3:-1] 
# Basically the starting index is last_index - 3 and ending index is last_index - 1 in above example so there it's 10 : 11

array([10, 11])

In [14]:
# Steps...
arr1[3:10:2]
# From 3 to 10 and with the gap of 1 between them  
# If we enter 3 the with the gap of 2.

array([3, 5, 7, 9])

In [17]:
arr1[::2]
# whole arr with the gap of 1 in between.

array([ 0,  2,  4,  6,  8, 10, 12])

In [33]:
# 2D array
arr2 = np.array([[1,2,3,4,5],
                 [6,7,8,9,0],
                 [11,22,33,44,55]])

In [30]:
#Getting element in 2D array 
arr2[1,2]

8

In [42]:
#Slicing in 2D array
arr2[0:2,0:2] , arr2[0:3,0:3] , arr2[1:3,2:4] 
#It's kinda trippy. so try as many combinations as you can and play around with it so you can get better understanding

(array([[1, 2],
        [6, 7]]),
 array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 22, 33]]),
 array([[ 8,  9],
        [33, 44]]))